"""Agregar titulo a examen

Revision ID: aef3d55d91d0
Revises: 4ee5fa4c4c19
Create Date: 2025-09-11 23:39:23.305391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef3d55d91d0'
down_revision = '4ee5fa4c4c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=255), nullable=False))
        batch_op.drop_column('respuesta_correcta')
        batch_op.drop_column('pregunta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pregunta', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('respuesta_correcta', sa.TEXT(), nullable=False))
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
