"""Agregar columna descripcion a curso

Revision ID: fdc6fc993124
Revises: aef3d55d91d0
Create Date: 2025-09-12 00:19:06.836394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc6fc993124'
down_revision = 'aef3d55d91d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    with op.batch_alter_table('curso_alumno', schema=None) as batch_op:
        batch_op.alter_column('curso_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('alumno_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso_alumno', schema=None) as batch_op:
        batch_op.alter_column('alumno_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('curso_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
